name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build 
      run: |
        cd server
        go build -v ./...
    - name: UnitTest
      run: |
        cd server
        go test -v ./tests/unit/
    - name: IntegrationTest
      run: |
        cd server
        go test -v ./tests/integration/
    - name: E2ETest
      run: |
        cd server
        go test -v ./tests/e2e/
